# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
from ultralytics import YOLO
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1390, 888)
        MainWindow.setStyleSheet("background-color: rgb(20, 20, 21);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 30, 1311, 771))
        self.frame.setStyleSheet("background-color: rgb(20, 22, 25);\n"
"border-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

## Label Video
        self.video_Label=QtWidgets.QLabel(self.frame)
        self.video_Label.setGeometry(QtCore.QRect(0,0,1311,771))
        self.video_Label.setStyleSheet("background-color: rgb(20, 22, 25);")
        self.video_Label.setObjectName("Video_Label")
## Label Video
        self.Btn_Next = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Next.setGeometry(QtCore.QRect(530, 820, 361, 51))
        self.Btn_Next.setStyleSheet("background-color: rgb(24, 29, 32);\n"
"color: rgb(215, 214, 216);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius:10px;\n"
"border:1px solid #505154;")
        self.Btn_Next.setObjectName("Btn_Next")
        self.Btn_Quit = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Quit.setGeometry(QtCore.QRect(20, 820, 51, 51))
        self.Btn_Quit.setStyleSheet("background-color: rgb(24, 29, 32);\n"
"color: rgb(215, 214, 216);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius:10px;\n"
"border:1px solid #505154;")
        self.Btn_Quit.setObjectName("Btn_Quit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


# تنظیمات مدل دوربین
        self.model= YOLO("yolov8n.pt")
        self.cap=None
        self.timer= QtCore.QTimer()
        self.timer.timeout.connect(self.Frame_Update)

        self.Btn_Next.clicked.connect(self.Start_Video)
        self.Btn_Quit.clicked.connect(self.quit_Form)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Next.setText(_translate("MainWindow", "Start"))
        self.Btn_Quit.setText(_translate("MainWindow", "Quit"))

    def Start_Video(self):
        if self.cap is None:
            self.cap=cv2.VideoCapture(0)
        if not self.timer.isActive():
            self.timer.start(30) 

    def Frame_Update(self):
        if self.cap:
            ret, frame = self.cap.read()
            if not ret:
                return

            results = self.model(frame, conf=0.4)
            annotated_frame = results[0].plot()
            object_count = len(results[0].boxes)
            cv2.putText(annotated_frame, f"Objects Detected: {object_count}", 
                        (10, 30), cv2.FONT_HERSHEY_COMPLEX,1, (255, 0, 0), 1)

            # Resize to QLabel size
            annotated_frame_resized = cv2.resize(annotated_frame, (1311, 771))
            image = QtGui.QImage(annotated_frame_resized.data, 1311, 771, 
                                 3 * 1311, QtGui.QImage.Format_BGR888)
            pixmap = QtGui.QPixmap.fromImage(image)
            self.video_Label.setPixmap(pixmap)



    def quit_Form(self):
        self.timer.stop()
        if self.cap:
            self.cap.release()
            self.cap=None

        QtWidgets.QApplication.quit()    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
